# Site settings
title: Diary of a madman
#email: mb7222@yandex.ru
description: > # this means to ignore newlines until "baseurl:"
  Блог
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tonymadbrain.github.io" # the base hostname & protocol for your site
twitter_username: tonymadbrain
github_username:  tonymadbrain

# Build settings
markdown: kramdown

#my settings
permalink: :title
paginate: 5
