# Site settings
title: Diary of a madman
#email: mb7222@yandex.ru
description: > # this means to ignore newlines until "baseurl:"
  <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/tonymadbrain" data-widget-id="458594999269986304">Твиты пользователя @tonymadbrain</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tonymadbrain.github.io" # the base hostname & protocol for your site
twitter_username: tonymadbrain
github_username:  tonymadbrain

# Build settings
markdown: kramdown

#my settings
permalink: :title
paginate: 5
